"""initial

Revision ID: 42d91d59f25d
Revises:
Create Date: 2022-03-25 16:47:41.065582

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "42d91d59f25d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column(
            "task_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="id задачи",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="имя задачи"),
        sa.Column(
            "processing_time",
            sa.Integer(),
            nullable=True,
            comment="время выполнения задачи",
        ),
        sa.Column("status", sa.SmallInteger(), nullable=True, comment="статус задачи"),
        sa.PrimaryKeyConstraint("task_id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks", schema="public")
    # ### end Alembic commands ###
